// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /serviceInterface.vm template.
 */
package ms.tfs.services.classification._03;

import com.microsoft.tfs.core.ws.runtime.exceptions.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.types.AnyContentType;

import ms.tfs.services.classification._03._Classification4Soap_CreateNode;
import ms.tfs.services.classification._03._Classification4Soap_CreateNodeResponse;
import ms.tfs.services.classification._03._Classification4Soap_CreateNodeWithDates;
import ms.tfs.services.classification._03._Classification4Soap_CreateNodeWithDatesResponse;
import ms.tfs.services.classification._03._Classification4Soap_CreateProject;
import ms.tfs.services.classification._03._Classification4Soap_CreateProjectResponse;
import ms.tfs.services.classification._03._Classification4Soap_DeleteBranches;
import ms.tfs.services.classification._03._Classification4Soap_DeleteBranchesResponse;
import ms.tfs.services.classification._03._Classification4Soap_DeleteProject;
import ms.tfs.services.classification._03._Classification4Soap_DeleteProjectResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetChangedNodes;
import ms.tfs.services.classification._03._Classification4Soap_GetChangedNodesAndProjects;
import ms.tfs.services.classification._03._Classification4Soap_GetChangedNodesAndProjectsResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetChangedNodesResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetDeletedNodesXml;
import ms.tfs.services.classification._03._Classification4Soap_GetDeletedNodesXmlResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetNode;
import ms.tfs.services.classification._03._Classification4Soap_GetNodeFromPath;
import ms.tfs.services.classification._03._Classification4Soap_GetNodeFromPathResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetNodeResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetNodesXml;
import ms.tfs.services.classification._03._Classification4Soap_GetNodesXmlResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetProject;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectFromName;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectFromNameResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectProperties;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectPropertiesResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectProperty;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectPropertyResponse;
import ms.tfs.services.classification._03._Classification4Soap_GetProjectResponse;
import ms.tfs.services.classification._03._Classification4Soap_ListAllProjects;
import ms.tfs.services.classification._03._Classification4Soap_ListAllProjectsResponse;
import ms.tfs.services.classification._03._Classification4Soap_ListProjects;
import ms.tfs.services.classification._03._Classification4Soap_ListProjectsResponse;
import ms.tfs.services.classification._03._Classification4Soap_ListStructures;
import ms.tfs.services.classification._03._Classification4Soap_ListStructuresResponse;
import ms.tfs.services.classification._03._Classification4Soap_MoveBranch;
import ms.tfs.services.classification._03._Classification4Soap_MoveBranchResponse;
import ms.tfs.services.classification._03._Classification4Soap_RenameNode;
import ms.tfs.services.classification._03._Classification4Soap_RenameNodeResponse;
import ms.tfs.services.classification._03._Classification4Soap_ReorderNode;
import ms.tfs.services.classification._03._Classification4Soap_ReorderNodeResponse;
import ms.tfs.services.classification._03._Classification4Soap_SetIterationDates;
import ms.tfs.services.classification._03._Classification4Soap_SetIterationDatesResponse;
import ms.tfs.services.classification._03._Classification4Soap_SetProjectProperty;
import ms.tfs.services.classification._03._Classification4Soap_SetProjectPropertyResponse;
import ms.tfs.services.classification._03._Classification4Soap_UpdateProjectProperties;
import ms.tfs.services.classification._03._Classification4Soap_UpdateProjectPropertiesResponse;
import ms.tfs.services.classification._03._NodeInfo;
import ms.tfs.services.classification._03._ProjectInfo;
import ms.tfs.services.classification._03._ProjectProperty;
import ms.tfs.services.classification._03._ProjectState;
import ms.tfs.services.classification._03._Property;

import java.lang.String;

import java.util.Calendar;

/**
 * Automatically generated service interface.
 *
 * {http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Classification/03}Classification4Soap
 */
public interface _Classification4Soap
{
    public String createNodeWithDates(
        final String nodeName,
        final String parentNodeUri,
        final Calendar startDate,
        final Calendar finishDate)
        throws TransportException, SOAPFault;

    public void setIterationDates(
        final String nodeUri,
        final Calendar startDate,
        final Calendar finishDate)
        throws TransportException, SOAPFault;

    public _ProjectProperty getProjectProperty(
        final String projectUri,
        final String name)
        throws TransportException, SOAPFault;

    public void setProjectProperty(
        final String projectUri,
        final String name,
        final String value)
        throws TransportException, SOAPFault;

    public String getChangedNodesAndProjects(final int firstSequenceId)
        throws TransportException, SOAPFault;

    public _ProjectInfo createProject(
        final String projectName,
        final AnyContentType structure)
        throws TransportException, SOAPFault;

    public void deleteProject(final String projectUri)
        throws TransportException, SOAPFault;

    public _Classification4Soap_GetProjectPropertiesResponse getProjectProperties(final String projectUri)
        throws TransportException, SOAPFault;

    public void updateProjectProperties(
        final String projectUri,
        final String state,
        final _ProjectProperty[] properties)
        throws TransportException, SOAPFault;

    public _ProjectInfo getProject(final String projectUri)
        throws TransportException, SOAPFault;

    public _ProjectInfo getProjectFromName(final String projectName)
        throws TransportException, SOAPFault;

    public _ProjectInfo[] listProjects()
        throws TransportException, SOAPFault;

    public _ProjectInfo[] listAllProjects()
        throws TransportException, SOAPFault;

    public _NodeInfo[] listStructures(final String projectUri)
        throws TransportException, SOAPFault;

    public AnyContentType getNodesXml(
        final String[] nodeUris,
        final boolean childNodes,
        final AnyContentType _out_getNodesXmlResult)
        throws TransportException, SOAPFault;

    public String createNode(
        final String nodeName,
        final String parentNodeUri)
        throws TransportException, SOAPFault;

    public void renameNode(
        final String nodeUri,
        final String newNodeName)
        throws TransportException, SOAPFault;

    public void moveBranch(
        final String nodeUri,
        final String newParentNodeUri)
        throws TransportException, SOAPFault;

    public void reorderNode(
        final String nodeUri,
        final int moveBy)
        throws TransportException, SOAPFault;

    public void deleteBranches(
        final String[] nodeUris,
        final String reclassifyUri)
        throws TransportException, SOAPFault;

    public AnyContentType getDeletedNodesXml(
        final String projectUri,
        final Calendar since,
        final AnyContentType _out_getDeletedNodesXmlResult)
        throws TransportException, SOAPFault;

    public _NodeInfo getNode(final String nodeUri)
        throws TransportException, SOAPFault;

    public _NodeInfo getNodeFromPath(final String nodePath)
        throws TransportException, SOAPFault;

    public String getChangedNodes(final int firstSequenceId)
        throws TransportException, SOAPFault;
}
