// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.services.classification._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.types.AnyContentType;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.services.classification._03._Classification4Soap_GetNodesXmlResponse;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _Classification4Soap_GetNodesXmlResponse
    implements ElementDeserializable
{
    // No attributes    

    // Elements
    protected AnyContentType getNodesXmlResult;

    public _Classification4Soap_GetNodesXmlResponse()
    {
        super();
    }

    public _Classification4Soap_GetNodesXmlResponse(final AnyContentType getNodesXmlResult)
    {
        // TODO : Call super() instead of setting all fields directly?
        setGetNodesXmlResult(getNodesXmlResult);
    }

    public AnyContentType getGetNodesXmlResult()
    {
        return this.getNodesXmlResult;
    }

    public void setGetNodesXmlResult(AnyContentType value)
    {
        this.getNodesXmlResult = value;
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // This object uses no attributes

        // Elements
        int event;

        do
        {
            event = reader.next();

            if (event == XMLStreamConstants.START_ELEMENT)
            {
                localName = reader.getLocalName();

                if (localName.equalsIgnoreCase("GetNodesXmlResult"))
                {
                    if (this.getNodesXmlResult == null)
                    {
                        throw new XMLStreamException(
                                "An AnyContentType implementation must be supplied by the caller "
                                + "for the 'getNodesXmlResult' field before deserialization can occur.");
                    }

                    this.getNodesXmlResult.readFromElement(reader);
                }
                else
                {
                    // Read the unknown child element until its end
                    XMLStreamReaderHelper.readUntilElementEnd(reader);
                }
            }
        }
        while (event != XMLStreamConstants.END_ELEMENT);
    }
}
