// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.services.classification._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.services.classification._03._Classification4Soap_GetNodeFromPathResponse;
import ms.tfs.services.classification._03._NodeInfo;
import ms.tfs.services.classification._03._Property;

import java.lang.String;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _Classification4Soap_GetNodeFromPathResponse
    implements ElementDeserializable
{
    // No attributes    

    // Elements
    protected _NodeInfo getNodeFromPathResult;

    public _Classification4Soap_GetNodeFromPathResponse()
    {
        super();
    }

    public _Classification4Soap_GetNodeFromPathResponse(final _NodeInfo getNodeFromPathResult)
    {
        // TODO : Call super() instead of setting all fields directly?
        setGetNodeFromPathResult(getNodeFromPathResult);
    }

    public _NodeInfo getGetNodeFromPathResult()
    {
        return this.getNodeFromPathResult;
    }

    public void setGetNodeFromPathResult(_NodeInfo value)
    {
        this.getNodeFromPathResult = value;
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // This object uses no attributes

        // Elements
        int event;

        do
        {
            event = reader.next();

            if (event == XMLStreamConstants.START_ELEMENT)
            {
                localName = reader.getLocalName();

                if (localName.equalsIgnoreCase("GetNodeFromPathResult"))
                {
                    this.getNodeFromPathResult = new _NodeInfo();
                    this.getNodeFromPathResult.readFromElement(reader);
                }
                else
                {
                    // Read the unknown child element until its end
                    XMLStreamReaderHelper.readUntilElementEnd(reader);
                }
            }
        }
        while (event != XMLStreamConstants.END_ELEMENT);
    }
}
