// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.services.classification._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.services.classification._03._ClassificationSoap_GetNodeFromPath;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _ClassificationSoap_GetNodeFromPath
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String nodePath;

    public _ClassificationSoap_GetNodeFromPath()
    {
        super();
    }

    public _ClassificationSoap_GetNodeFromPath(final String nodePath)
    {
        // TODO : Call super() instead of setting all fields directly?
        setNodePath(nodePath);
    }

    public String getNodePath()
    {
        return this.nodePath;
    }

    public void setNodePath(String value)
    {
        this.nodePath = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "nodePath",
            this.nodePath);

        writer.writeEndElement();
    }
}
