// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.versioncontrol.clientservices._03._Change;
import ms.tfs.versioncontrol.clientservices._03._ChangeType;
import ms.tfs.versioncontrol.clientservices._03._Changeset;
import ms.tfs.versioncontrol.clientservices._03._ChangesetMergeDetails;
import ms.tfs.versioncontrol.clientservices._03._CheckinNote;
import ms.tfs.versioncontrol.clientservices._03._CheckinNoteFieldValue;
import ms.tfs.versioncontrol.clientservices._03._Item;
import ms.tfs.versioncontrol.clientservices._03._ItemMerge;
import ms.tfs.versioncontrol.clientservices._03._ItemType;
import ms.tfs.versioncontrol.clientservices._03._MergeSource;
import ms.tfs.versioncontrol.clientservices._03._PolicyFailureInfo;
import ms.tfs.versioncontrol.clientservices._03._PolicyOverrideInfo;
import ms.tfs.versioncontrol.clientservices._03._PropertyValue;

import java.lang.Object;
import java.lang.String;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _ChangesetMergeDetails
    implements ElementSerializable, ElementDeserializable
{
    // No attributes    

    // Elements
    protected _ItemMerge[] mergedItems;
    protected _ItemMerge[] unmergedItems;
    protected _Changeset[] changesets;

    public _ChangesetMergeDetails()
    {
        super();
    }

    public _ChangesetMergeDetails(
        final _ItemMerge[] mergedItems,
        final _ItemMerge[] unmergedItems,
        final _Changeset[] changesets)
    {
        // TODO : Call super() instead of setting all fields directly?
        setMergedItems(mergedItems);
        setUnmergedItems(unmergedItems);
        setChangesets(changesets);
    }

    public _ItemMerge[] getMergedItems()
    {
        return this.mergedItems;
    }

    public void setMergedItems(_ItemMerge[] value)
    {
        this.mergedItems = value;
    }

    public _ItemMerge[] getUnmergedItems()
    {
        return this.unmergedItems;
    }

    public void setUnmergedItems(_ItemMerge[] value)
    {
        this.unmergedItems = value;
    }

    public _Changeset[] getChangesets()
    {
        return this.changesets;
    }

    public void setChangesets(_Changeset[] value)
    {
        this.changesets = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        if (this.mergedItems != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("MergedItems");

            for (int iterator0 = 0; iterator0 < this.mergedItems.length; iterator0++)
            {
                this.mergedItems[iterator0].writeAsElement(
                    writer,
                    "ItemMerge");
            }

            writer.writeEndElement();
        }

        if (this.unmergedItems != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("UnmergedItems");

            for (int iterator0 = 0; iterator0 < this.unmergedItems.length; iterator0++)
            {
                this.unmergedItems[iterator0].writeAsElement(
                    writer,
                    "ItemMerge");
            }

            writer.writeEndElement();
        }

        if (this.changesets != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("Changesets");

            for (int iterator0 = 0; iterator0 < this.changesets.length; iterator0++)
            {
                this.changesets[iterator0].writeAsElement(
                    writer,
                    "Changeset");
            }

            writer.writeEndElement();
        }

        writer.writeEndElement();
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // This object uses no attributes

        // Elements
        int event;

        do
        {
            event = reader.next();

            if (event == XMLStreamConstants.START_ELEMENT)
            {
                localName = reader.getLocalName();

                if (localName.equalsIgnoreCase("MergedItems"))
                {
                    /*
                     * The element type is an array.
                     */
                    int event0;
                    final List list0 = new ArrayList();

                    do
                    {
                        event0 = reader.nextTag();

                        if (event0 == XMLStreamConstants.START_ELEMENT)
                        {
                            _ItemMerge complexObject0 = new _ItemMerge();
                            complexObject0.readFromElement(reader);
                            list0.add(complexObject0);
                        }
                    }
                    while (event0 != XMLStreamConstants.END_ELEMENT);

                    this.mergedItems = (_ItemMerge[]) list0.toArray(new _ItemMerge[list0.size()]);
                }
                else if (localName.equalsIgnoreCase("UnmergedItems"))
                {
                    /*
                     * The element type is an array.
                     */
                    int event0;
                    final List list0 = new ArrayList();

                    do
                    {
                        event0 = reader.nextTag();

                        if (event0 == XMLStreamConstants.START_ELEMENT)
                        {
                            _ItemMerge complexObject0 = new _ItemMerge();
                            complexObject0.readFromElement(reader);
                            list0.add(complexObject0);
                        }
                    }
                    while (event0 != XMLStreamConstants.END_ELEMENT);

                    this.unmergedItems = (_ItemMerge[]) list0.toArray(new _ItemMerge[list0.size()]);
                }
                else if (localName.equalsIgnoreCase("Changesets"))
                {
                    /*
                     * The element type is an array.
                     */
                    int event0;
                    final List list0 = new ArrayList();

                    do
                    {
                        event0 = reader.nextTag();

                        if (event0 == XMLStreamConstants.START_ELEMENT)
                        {
                            _Changeset complexObject0 = new _Changeset();
                            complexObject0.readFromElement(reader);
                            list0.add(complexObject0);
                        }
                    }
                    while (event0 != XMLStreamConstants.END_ELEMENT);

                    this.changesets = (_Changeset[]) list0.toArray(new _Changeset[list0.size()]);
                }
                else
                {
                    // Read the unknown child element until its end
                    XMLStreamReaderHelper.readUntilElementEnd(reader);
                }
            }
        }
        while (event != XMLStreamConstants.END_ELEMENT);
    }
}
