// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.versioncontrol.clientservices._03._ItemSpec;
import ms.tfs.versioncontrol.clientservices._03._LabelItemSpec;
import ms.tfs.versioncontrol.clientservices._03._RecursionType;
import ms.tfs.versioncontrol.clientservices._03._VersionSpec;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _LabelItemSpec
    implements ElementSerializable, ElementDeserializable
{
    // Attributes
    protected boolean ex = false;

    // Elements
    protected _ItemSpec itemSpec;
    protected _VersionSpec version;

    public _LabelItemSpec()
    {
        super();
    }

    public _LabelItemSpec(
        final boolean ex,
        final _ItemSpec itemSpec,
        final _VersionSpec version)
    {
        // TODO : Call super() instead of setting all fields directly?
        setEx(ex);
        setItemSpec(itemSpec);
        setVersion(version);
    }

    public boolean isEx()
    {
        return this.ex;
    }

    public void setEx(final boolean value)
    {
        this.ex = value;
    }

    public _ItemSpec getItemSpec()
    {
        return this.itemSpec;
    }

    public void setItemSpec(_ItemSpec value)
    {
        this.itemSpec = value;
    }

    public _VersionSpec getVersion()
    {
        return this.version;
    }

    public void setVersion(_VersionSpec value)
    {
        this.version = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Attributes
        XMLStreamWriterHelper.writeAttribute(
            writer,
            "ex",
            this.ex);

        // Elements
        if (this.itemSpec != null)
        {
            this.itemSpec.writeAsElement(
                writer,
                "ItemSpec");
        }

        if (this.version != null)
        {
            this.version.writeAsElement(
                writer,
                "Version");
        }

        writer.writeEndElement();
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // Attributes
        final int attributeCount = reader.getAttributeCount();
        String attributeValue;

        for (int i = 0; i < attributeCount; i++)
        {
            localName = reader.getAttributeLocalName(i);
            attributeValue = reader.getAttributeValue(i);

            if (localName.equalsIgnoreCase("ex"))
            {
                this.ex = XMLConvert.toBoolean(attributeValue);
            }

            // Ignore unknown attributes.
        }

        // Elements
        int event;

        do
        {
            event = reader.next();

            if (event == XMLStreamConstants.START_ELEMENT)
            {
                localName = reader.getLocalName();

                if (localName.equalsIgnoreCase("ItemSpec"))
                {
                    this.itemSpec = new _ItemSpec();
                    this.itemSpec.readFromElement(reader);
                }
                else if (localName.equalsIgnoreCase("Version"))
                {
                    /*
                     * The element is an abstract type, so prepare to deserialize all the
                     * known derived types.
                     */
                    final String typeAttribute = reader.getAttributeValue(
                            Schemas.XSI,
                            "type");

                    if (typeAttribute == null)
                    {
                        throw new XMLStreamException(
                                "Element " + reader.getLocalName()
                                + " is for a derived type but did not include a type attribute");
                    }

                    if (typeAttribute.equals("ChangesetVersionSpec"))
                    {
                        this.version = new _ChangesetVersionSpec();
                    }
                    else if (typeAttribute.equals("DateVersionSpec"))
                    {
                        this.version = new _DateVersionSpec();
                    }
                    else if (typeAttribute.equals("LabelVersionSpec"))
                    {
                        this.version = new _LabelVersionSpec();
                    }
                    else if (typeAttribute.equals("LatestVersionSpec"))
                    {
                        this.version = new _LatestVersionSpec();
                    }
                    else if (typeAttribute.equals("WorkspaceVersionSpec"))
                    {
                        this.version = new _WorkspaceVersionSpec();
                    }

                    this.version.readFromElement(reader);
                }
                else
                {
                    // Read the unknown child element until its end
                    XMLStreamReaderHelper.readUntilElementEnd(reader);
                }
            }
        }
        while (event != XMLStreamConstants.END_ELEMENT);
    }
}
