// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.versioncontrol.clientservices._03._LabelResult;
import ms.tfs.versioncontrol.clientservices._03._LabelResultStatus;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _LabelResult
    implements ElementSerializable, ElementDeserializable
{
    // Attributes
    protected String label;
    protected String scope;
    protected _LabelResultStatus status;

    // No elements    
    public _LabelResult()
    {
        super();
    }

    public _LabelResult(
        final String label,
        final String scope,
        final _LabelResultStatus status)
    {
        // TODO : Call super() instead of setting all fields directly?
        setLabel(label);
        setScope(scope);
        setStatus(status);
    }

    public String getLabel()
    {
        return this.label;
    }

    public void setLabel(final String value)
    {
        this.label = value;
    }

    public String getScope()
    {
        return this.scope;
    }

    public void setScope(final String value)
    {
        this.scope = value;
    }

    public _LabelResultStatus getStatus()
    {
        return this.status;
    }

    public void setStatus(final _LabelResultStatus value)
    {
        if (value == null)
        {
            throw new IllegalArgumentException("'status' is a required attribute, its value cannot be null");
        }

        this.status = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Attributes
        XMLStreamWriterHelper.writeAttribute(
            writer,
            "label",
            this.label);
        XMLStreamWriterHelper.writeAttribute(
            writer,
            "scope",
            this.scope);
        this.status.writeAsAttribute(
            writer,
            "status");

        writer.writeEndElement();
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // Attributes
        final int attributeCount = reader.getAttributeCount();
        String attributeValue;

        for (int i = 0; i < attributeCount; i++)
        {
            localName = reader.getAttributeLocalName(i);
            attributeValue = reader.getAttributeValue(i);

            if (localName.equalsIgnoreCase("label"))
            {
                this.label = attributeValue;
            }
            else if (localName.equalsIgnoreCase("scope"))
            {
                this.scope = attributeValue;
            }
            else if (localName.equalsIgnoreCase("status"))
            {
                this.status = _LabelResultStatus.fromString(attributeValue);
            }

            // Ignore unknown attributes.
        }

        // This object uses no elements, so read until our element end
        XMLStreamReaderHelper.readUntilElementEnd(reader);
    }
}
