// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.versioncontrol.clientservices._03._RepositorySoap_UpdateWorkspace;
import ms.tfs.versioncontrol.clientservices._03._WorkingFolder;
import ms.tfs.versioncontrol.clientservices._03._WorkingFolderType;
import ms.tfs.versioncontrol.clientservices._03._Workspace;

import java.lang.String;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _RepositorySoap_UpdateWorkspace
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String oldWorkspaceName;
    protected String ownerName;
    protected _Workspace newWorkspace;
    protected int supportedFeatures;

    public _RepositorySoap_UpdateWorkspace()
    {
        super();
    }

    public _RepositorySoap_UpdateWorkspace(
        final String oldWorkspaceName,
        final String ownerName,
        final _Workspace newWorkspace,
        final int supportedFeatures)
    {
        // TODO : Call super() instead of setting all fields directly?
        setOldWorkspaceName(oldWorkspaceName);
        setOwnerName(ownerName);
        setNewWorkspace(newWorkspace);
        setSupportedFeatures(supportedFeatures);
    }

    public String getOldWorkspaceName()
    {
        return this.oldWorkspaceName;
    }

    public void setOldWorkspaceName(String value)
    {
        this.oldWorkspaceName = value;
    }

    public String getOwnerName()
    {
        return this.ownerName;
    }

    public void setOwnerName(String value)
    {
        this.ownerName = value;
    }

    public _Workspace getNewWorkspace()
    {
        return this.newWorkspace;
    }

    public void setNewWorkspace(_Workspace value)
    {
        this.newWorkspace = value;
    }

    public int getSupportedFeatures()
    {
        return this.supportedFeatures;
    }

    public void setSupportedFeatures(int value)
    {
        this.supportedFeatures = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "oldWorkspaceName",
            this.oldWorkspaceName);
        XMLStreamWriterHelper.writeElement(
            writer,
            "ownerName",
            this.ownerName);

        if (this.newWorkspace != null)
        {
            this.newWorkspace.writeAsElement(
                writer,
                "newWorkspace");
        }

        XMLStreamWriterHelper.writeElement(
            writer,
            "supportedFeatures",
            this.supportedFeatures);

        writer.writeEndElement();
    }
}
