// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.versioncontrol.clientservices._03._ItemSpec;
import ms.tfs.versioncontrol.clientservices._03._RecursionType;
import ms.tfs.versioncontrol.clientservices._03._RepositoryExtensionsSoap_QueryBranchObjectOwnership;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _RepositoryExtensionsSoap_QueryBranchObjectOwnership
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected int[] changesets;
    protected _ItemSpec pathFilter;

    public _RepositoryExtensionsSoap_QueryBranchObjectOwnership()
    {
        super();
    }

    public _RepositoryExtensionsSoap_QueryBranchObjectOwnership(
        final int[] changesets,
        final _ItemSpec pathFilter)
    {
        // TODO : Call super() instead of setting all fields directly?
        setChangesets(changesets);
        setPathFilter(pathFilter);
    }

    public int[] getChangesets()
    {
        return this.changesets;
    }

    public void setChangesets(int[] value)
    {
        this.changesets = value;
    }

    public _ItemSpec getPathFilter()
    {
        return this.pathFilter;
    }

    public void setPathFilter(_ItemSpec value)
    {
        this.pathFilter = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        if (this.changesets != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("changesets");

            for (int iterator0 = 0; iterator0 < this.changesets.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "int",
                    this.changesets[iterator0]);
            }

            writer.writeEndElement();
        }

        if (this.pathFilter != null)
        {
            this.pathFilter.writeAsElement(
                writer,
                "pathFilter");
        }

        writer.writeEndElement();
    }
}
