// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /enumeration.vm template.
 */
package ms.tfs.versioncontrol.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.exceptions.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;

import java.util.HashMap;
import java.util.Map;

/**
 * Automatically generated enumeration class.
 */
public final class _RequestType
    extends Enumeration
{
    /**
     * This map lets static methods in this class map strings to
     * the correct instance type at deserialization time.
     */
    private final static Map VALUES_TO_INSTANCES = new HashMap();
    public static final _RequestType None = new _RequestType("None");
    public static final _RequestType Add = new _RequestType("Add");
    public static final _RequestType Branch = new _RequestType("Branch");
    public static final _RequestType Encoding = new _RequestType("Encoding");
    public static final _RequestType Edit = new _RequestType("Edit");
    public static final _RequestType Delete = new _RequestType("Delete");
    public static final _RequestType Lock = new _RequestType("Lock");
    public static final _RequestType Rename = new _RequestType("Rename");
    public static final _RequestType Undelete = new _RequestType("Undelete");
    public static final _RequestType Property = new _RequestType("Property");

    private _RequestType(final String name)
    {
        super(name, _RequestType.VALUES_TO_INSTANCES);
    }

    /**
     * Gets the specific enumeration value in this class appropriate for the given
     * XML attribute value.  If no value is known, null is returned (_DEFAULT is not used; that
     * value is for when the attribute is not present).
     *
     * @param value
     *        the XML attribute value (not null)
     * @return the appropriate enumeration instance.
     */
    public static _RequestType fromString(final String value)
        throws SOAPSerializationException
    {
        return (_RequestType) Enumeration.fromString(
            value,
            _RequestType.VALUES_TO_INSTANCES);
    }
}
