// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.workitemtracking.clientservices._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.workitemtracking.clientservices._03._ClientService2Soap_PageWorkitemsByIds;
import ms.tfs.workitemtracking.clientservices._03._MetadataTableHaveEntry;

import java.lang.String;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _ClientService2Soap_PageWorkitemsByIds
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected int[] ids;
    protected String[] columns;
    protected int[] longTextColumns;
    protected Calendar asOfDate;
    protected boolean useMaster;
    protected _MetadataTableHaveEntry[] metadataHave;

    public _ClientService2Soap_PageWorkitemsByIds()
    {
        super();
    }

    public _ClientService2Soap_PageWorkitemsByIds(
        final int[] ids,
        final String[] columns,
        final int[] longTextColumns,
        final Calendar asOfDate,
        final boolean useMaster,
        final _MetadataTableHaveEntry[] metadataHave)
    {
        // TODO : Call super() instead of setting all fields directly?
        setIds(ids);
        setColumns(columns);
        setLongTextColumns(longTextColumns);
        setAsOfDate(asOfDate);
        setUseMaster(useMaster);
        setMetadataHave(metadataHave);
    }

    public int[] getIds()
    {
        return this.ids;
    }

    public void setIds(int[] value)
    {
        this.ids = value;
    }

    public String[] getColumns()
    {
        return this.columns;
    }

    public void setColumns(String[] value)
    {
        this.columns = value;
    }

    public int[] getLongTextColumns()
    {
        return this.longTextColumns;
    }

    public void setLongTextColumns(int[] value)
    {
        this.longTextColumns = value;
    }

    public Calendar getAsOfDate()
    {
        return this.asOfDate;
    }

    public void setAsOfDate(Calendar value)
    {
        this.asOfDate = value;
    }

    public boolean isUseMaster()
    {
        return this.useMaster;
    }

    public void setUseMaster(boolean value)
    {
        this.useMaster = value;
    }

    public _MetadataTableHaveEntry[] getMetadataHave()
    {
        return this.metadataHave;
    }

    public void setMetadataHave(_MetadataTableHaveEntry[] value)
    {
        this.metadataHave = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        if (this.ids != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("ids");

            for (int iterator0 = 0; iterator0 < this.ids.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "int",
                    this.ids[iterator0]);
            }

            writer.writeEndElement();
        }

        if (this.columns != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("columns");

            for (int iterator0 = 0; iterator0 < this.columns.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "string",
                    this.columns[iterator0]);
            }

            writer.writeEndElement();
        }

        if (this.longTextColumns != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("longTextColumns");

            for (int iterator0 = 0; iterator0 < this.longTextColumns.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "int",
                    this.longTextColumns[iterator0]);
            }

            writer.writeEndElement();
        }

        XMLStreamWriterHelper.writeElement(
            writer,
            "asOfDate",
            this.asOfDate,
            true);
        XMLStreamWriterHelper.writeElement(
            writer,
            "useMaster",
            this.useMaster);

        if (this.metadataHave != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("metadataHave");

            for (int iterator0 = 0; iterator0 < this.metadataHave.length; iterator0++)
            {
                this.metadataHave[iterator0].writeAsElement(
                    writer,
                    "MetadataTableHaveEntry");
            }

            writer.writeEndElement();
        }

        writer.writeEndElement();
    }
}
