// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /serviceImplementation.vm template.
 */
package ms.tfs.versioncontrol.statistics._03;

import com.microsoft.tfs.core.httpclient.HttpClient;
import com.microsoft.tfs.core.ws.runtime.client.*;
import com.microsoft.tfs.core.ws.runtime.exceptions.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;

import ms.tfs.versioncontrol.statistics._03._ProxyStatisticsInfo;
import ms.tfs.versioncontrol.statistics._03._ProxyStatisticsWebServiceSoap_QueryProxyStatistics;
import ms.tfs.versioncontrol.statistics._03._ProxyStatisticsWebServiceSoap_QueryProxyStatisticsResponse;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import java.lang.String;

import java.net.URI;

import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated service interface.
 *
 * {http://schemas.microsoft.com/TeamFoundation/2005/06/VersionControl/Statistics/03}ProxyStatisticsWebServiceSoapService
 */
public class _ProxyStatisticsWebServiceSoapService
    extends SOAP11Service
    implements _ProxyStatisticsWebServiceSoap
{
    private static final QName PORT_QNAME = new QName(
                "http://schemas.microsoft.com/TeamFoundation/2005/06/VersionControl/Statistics/03",
                "ProxyStatisticsWebServiceSoapService");
    private static final String ENDPOINT_PATH = "/tfs/DefaultCollection/VersionControl/v1.0/ProxyStatistics.asmx";

    public _ProxyStatisticsWebServiceSoapService(
        final URI endpoint,
        final QName port)
    {
        super(endpoint, port);
    }

    public _ProxyStatisticsWebServiceSoapService(
        final HttpClient client,
        URI endpoint,
        QName port)
    {
        super(client, endpoint, port);
    }

    /**
     * @return the qualified name of the WSDL port this service implementation can be used with
     */
    public static QName getPortQName()
    {
        return _ProxyStatisticsWebServiceSoapService.PORT_QNAME;
    }

    /**
     * @return the path part to use when constructing a URI to contact a host that provides this service
     */
    public static String getEndpointPath()
    {
        return _ProxyStatisticsWebServiceSoapService.ENDPOINT_PATH;
    }

    public _ProxyStatisticsInfo[] queryProxyStatistics()
        throws TransportException, SOAPFault
    {
        final _ProxyStatisticsWebServiceSoap_QueryProxyStatistics requestData = new _ProxyStatisticsWebServiceSoap_QueryProxyStatistics();

        final SOAPRequest request = createSOAPRequest(
                "QueryProxyStatistics",
                new SOAPMethodRequestWriter()
                {
                    public void writeSOAPRequest(
                        final XMLStreamWriter writer,
                        final OutputStream out)
                        throws XMLStreamException, IOException
                    {
                        requestData.writeAsElement(
                            writer,
                            "QueryProxyStatistics");
                    }
                });

        final _ProxyStatisticsWebServiceSoap_QueryProxyStatisticsResponse responseData = new _ProxyStatisticsWebServiceSoap_QueryProxyStatisticsResponse();

        executeSOAPRequest(
            request,
            "QueryProxyStatisticsResponse",
            new SOAPMethodResponseReader()
            {
                public void readSOAPResponse(
                    final XMLStreamReader reader,
                    final InputStream in)
                    throws XMLStreamException, IOException
                {
                    responseData.readFromElement(reader);
                }
            });

        return responseData.getQueryProxyStatisticsResult();
    }
}
