// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.tfs.services.groupsecurity._03;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.tfs.services.groupsecurity._03._GroupSecurityServiceSoap_DeleteApplicationGroup;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _GroupSecurityServiceSoap_DeleteApplicationGroup
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String groupSid;

    public _GroupSecurityServiceSoap_DeleteApplicationGroup()
    {
        super();
    }

    public _GroupSecurityServiceSoap_DeleteApplicationGroup(final String groupSid)
    {
        // TODO : Call super() instead of setting all fields directly?
        setGroupSid(groupSid);
    }

    public String getGroupSid()
    {
        return this.groupSid;
    }

    public void setGroupSid(String value)
    {
        this.groupSid = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "groupSid",
            this.groupSid);

        writer.writeEndElement();
    }
}
