// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /serviceInterface.vm template.
 */
package ms.tfs.workitemtracking.configurationsettingsservice._03;

import com.microsoft.tfs.core.ws.runtime.exceptions.*;
import com.microsoft.tfs.core.ws.runtime.types.*;

import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetInProcBuildCompletionNotificationAvailability;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetInProcBuildCompletionNotificationAvailabilityResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetMaxAttachmentSize;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetMaxAttachmentSizeResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetMaxBuildListSize;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetMaxBuildListSizeResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetWorkItemQueryTimeout;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetWorkItemQueryTimeoutResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetWorkitemTrackingVersion;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_GetWorkitemTrackingVersionResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetInProcBuildCompletionNotificationAvailability;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetInProcBuildCompletionNotificationAvailabilityResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetMaxAttachmentSize;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetMaxAttachmentSizeResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetMaxBuildListSize;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetMaxBuildListSizeResponse;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetWorkItemQueryTimeout;
import ms.tfs.workitemtracking.configurationsettingsservice._03._ConfigurationSettingsServiceSoap_SetWorkItemQueryTimeoutResponse;

import java.lang.String;

/**
 * Automatically generated service interface.
 *
 * {http://schemas.microsoft.com/TeamFoundation/2005/06/WorkItemTracking/configurationSettingsService/03}ConfigurationSettingsServiceSoap
 */
public interface _ConfigurationSettingsServiceSoap
{
    public String getWorkitemTrackingVersion()
        throws TransportException, SOAPFault;

    public long getMaxAttachmentSize()
        throws TransportException, SOAPFault;

    public void setMaxAttachmentSize(final long maxSize)
        throws TransportException, SOAPFault;

    public boolean getInProcBuildCompletionNotificationAvailability()
        throws TransportException, SOAPFault;

    public void setInProcBuildCompletionNotificationAvailability(final boolean isEnabled)
        throws TransportException, SOAPFault;

    public int getMaxBuildListSize()
        throws TransportException, SOAPFault;

    public void setMaxBuildListSize(final int maxBuildListSize)
        throws TransportException, SOAPFault;

    public int getWorkItemQueryTimeout()
        throws TransportException, SOAPFault;

    public void setWorkItemQueryTimeout(final int workItemQueryTimeout)
        throws TransportException, SOAPFault;
}
