// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.ws;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.ws._AccessControlEntry;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _AccessControlEntry
    implements ElementSerializable, ElementDeserializable
{
    // Attributes
    protected int allow;
    protected int deny;

    // No elements    
    public _AccessControlEntry()
    {
        super();
    }

    public _AccessControlEntry(
        final int allow,
        final int deny)
    {
        // TODO : Call super() instead of setting all fields directly?
        setAllow(allow);
        setDeny(deny);
    }

    public int getAllow()
    {
        return this.allow;
    }

    public void setAllow(final int value)
    {
        this.allow = value;
    }

    public int getDeny()
    {
        return this.deny;
    }

    public void setDeny(final int value)
    {
        this.deny = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Attributes
        XMLStreamWriterHelper.writeAttribute(
            writer,
            "Allow",
            this.allow);
        XMLStreamWriterHelper.writeAttribute(
            writer,
            "Deny",
            this.deny);

        writer.writeEndElement();
    }

    public void readFromElement(final XMLStreamReader reader)
        throws XMLStreamException
    {
        String localName;

        // Attributes
        final int attributeCount = reader.getAttributeCount();
        String attributeValue;

        for (int i = 0; i < attributeCount; i++)
        {
            localName = reader.getAttributeLocalName(i);
            attributeValue = reader.getAttributeValue(i);

            if (localName.equalsIgnoreCase("Allow"))
            {
                this.allow = XMLConvert.toInt(attributeValue);
            }
            else if (localName.equalsIgnoreCase("Deny"))
            {
                this.deny = XMLConvert.toInt(attributeValue);
            }

            // Ignore unknown attributes.
        }

        // This object uses no elements, so read until our element end
        XMLStreamReaderHelper.readUntilElementEnd(reader);
    }
}
