// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.ws;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.ws._CatalogWebServiceSoap_QueryParents;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _CatalogWebServiceSoap_QueryParents
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String resourceIdentifier;
    protected String[] pathFilters;
    protected String[] resourceTypeFilters;
    protected boolean recurseToRoot;
    protected int queryOptions;

    public _CatalogWebServiceSoap_QueryParents()
    {
        super();
    }

    public _CatalogWebServiceSoap_QueryParents(
        final String resourceIdentifier,
        final String[] pathFilters,
        final String[] resourceTypeFilters,
        final boolean recurseToRoot,
        final int queryOptions)
    {
        // TODO : Call super() instead of setting all fields directly?
        setResourceIdentifier(resourceIdentifier);
        setPathFilters(pathFilters);
        setResourceTypeFilters(resourceTypeFilters);
        setRecurseToRoot(recurseToRoot);
        setQueryOptions(queryOptions);
    }

    public String getResourceIdentifier()
    {
        return this.resourceIdentifier;
    }

    public void setResourceIdentifier(String value)
    {
        if (value == null)
        {
            throw new IllegalArgumentException("'resourceIdentifier' is a required element, its value cannot be null");
        }

        this.resourceIdentifier = value;
    }

    public String[] getPathFilters()
    {
        return this.pathFilters;
    }

    public void setPathFilters(String[] value)
    {
        this.pathFilters = value;
    }

    public String[] getResourceTypeFilters()
    {
        return this.resourceTypeFilters;
    }

    public void setResourceTypeFilters(String[] value)
    {
        this.resourceTypeFilters = value;
    }

    public boolean isRecurseToRoot()
    {
        return this.recurseToRoot;
    }

    public void setRecurseToRoot(boolean value)
    {
        this.recurseToRoot = value;
    }

    public int getQueryOptions()
    {
        return this.queryOptions;
    }

    public void setQueryOptions(int value)
    {
        this.queryOptions = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "resourceIdentifier",
            this.resourceIdentifier);

        if (this.pathFilters != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("pathFilters");

            for (int iterator0 = 0; iterator0 < this.pathFilters.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "string",
                    this.pathFilters[iterator0]);
            }

            writer.writeEndElement();
        }

        if (this.resourceTypeFilters != null)
        {
            /*
             * The element type is an array.
             */
            writer.writeStartElement("resourceTypeFilters");

            for (int iterator0 = 0; iterator0 < this.resourceTypeFilters.length; iterator0++)
            {
                XMLStreamWriterHelper.writeElement(
                    writer,
                    "guid",
                    this.resourceTypeFilters[iterator0]);
            }

            writer.writeEndElement();
        }

        XMLStreamWriterHelper.writeElement(
            writer,
            "recurseToRoot",
            this.recurseToRoot);
        XMLStreamWriterHelper.writeElement(
            writer,
            "queryOptions",
            this.queryOptions);

        writer.writeEndElement();
    }
}
