// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

package com.microsoft.tfs.core.clients.workitem.internal;

public class QueryPackageNames {
    public static final String QUERY_AS_OF = "AsOf"; //$NON-NLS-1$
    public static final String QUERY_EVER = "Ever"; //$NON-NLS-1$
    public static final String GROUP_OPERATOR = "GroupOperator"; //$NON-NLS-1$
    public static final String OPERATOR_AND = "and"; //$NON-NLS-1$
    public static final String OPERATOR_OR = "or"; //$NON-NLS-1$
    public static final String OPERATOR_AND_NOT = "andnot"; //$NON-NLS-1$
    public static final String OPERATOR_OR_NOT = "ornot"; //$NON-NLS-1$
    public static final String EXPRESSION = "Expression"; //$NON-NLS-1$
    public static final String GROUP = "Group"; //$NON-NLS-1$
    public static final String OPERATOR = "Operator"; //$NON-NLS-1$
    public static final String FIELD_TYPE = "FieldType"; //$NON-NLS-1$
    public static final String VALUE_TYPE_STRING = "String"; //$NON-NLS-1$
    public static final String VALUE_TYPE_NUMBER = "Number"; //$NON-NLS-1$
    public static final String VALUE_TYPE_DOUBLE = "Double"; //$NON-NLS-1$
    public static final String VALUE_TYPE_DATE_TIME = "DateTime"; //$NON-NLS-1$
    public static final String VALUE_TYPE_BOOLEAN = "Boolean"; //$NON-NLS-1$
    public static final String VALUE_TYPE_GUID = "Guid"; //$NON-NLS-1$
    public static final String VALUE_TYPE_COLUMN = "Column"; //$NON-NLS-1$
    public static final String EXPAND_CONSTANT = "ExpandConstant"; //$NON-NLS-1$
    public static final String EXCLUDE_LOWER = "ExcludeLower"; //$NON-NLS-1$
    public static final String EXCLUDE_UPPER = "ExcludeUpper"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_EQUALS = "equals"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOT_EQUALS = "notequals"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_LESS = "less"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_LESS_EQUALS = "equalsless"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_GREATER = "greater"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_GREATER_EQUALS = "equalsgreater"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_EVER = "ever"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_CONTAINS = "contains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOT_CONTAINS = "notcontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_UNDER = "under"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOT_UNDER = "notunder"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_EVER_CONTAINS = "evercontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NEVER_CONTAINS = "nevercontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATORFT_CONTAINS = "ftcontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOTFT_CONTAINS = "notftcontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_EVERFT_CONTAINS = "everftcontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NEVERFT_CONTAINS = "neverftcontains"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_BEGINS_WITH = "beginswith"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOT_BEGINS_WITH = "notbeginswith"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_REF = "ref"; //$NON-NLS-1$
    public static final String EXPRESSION_OPERATOR_NOT_REF = "notref"; //$NON-NLS-1$
    public static final String QUERY_LINKS_ELEMENT = "LinksQuery"; //$NON-NLS-1$
    public static final String QUERY_LINKS_LEFT_QUERY_ELEMENT = "LeftQuery"; //$NON-NLS-1$
    public static final String QUERY_LINKS_LEFT_QUERY_PREFIX = "lhs"; //$NON-NLS-1$
    public static final String QUERY_LINKS_LINK_QUERY_ELEMENT = "LinkQuery"; //$NON-NLS-1$
    public static final String QUERY_LINKS_LINK_QUERY_PREFIX = "links"; //$NON-NLS-1$
    public static final String QUERY_LINKS_LINK_TYPE_QUERY_PREFIX = "linktypes"; //$NON-NLS-1$
    public static final String QUERY_LINKS_RIGHT_QUERY_ELEMENT = "RightQuery"; //$NON-NLS-1$
    public static final String QUERY_LINKS_RIGHT_QUERY_PREFIX = "rhs"; //$NON-NLS-1$
    public static final String QUERY_LINKS_RECURSIVE_ATTRIBUTE = "RecursionID"; //$NON-NLS-1$
    public static final String QUERY_LINKS_TYPE_ATTRIBUTE = "Type"; //$NON-NLS-1$
    public static final String QUERY_LINKS_MUST_CONTAIN_TYPE = "mustcontain"; //$NON-NLS-1$
    public static final String QUERY_LINKS_MAY_CONTAIN_TYPE = "maycontain"; //$NON-NLS-1$
    public static final String QUERY_LINKS_DOES_NOT_CONTAIN_TYPE = "doesnotcontain"; //$NON-NLS-1$
    public static final int FIELDS_TYPE_MASK_DATA_TYPE = 240;
    public static final int FIELDS_TYPE_MASK_SUB_TYPE = 3840;
    public static final int FIELDS_TYPE_MASK_READ_ONLY = 1;
    public static final int FIELDS_TYPE_MASK_IGNORE = 2;
    public static final int FIELDS_TYPE_MASK_PERSON = 8;
    public static final int FIELDS_TYPE_KEYWORD = 16;
    public static final int FIELDS_TYPE_INTEGER = 32;
    public static final int FIELDS_TYPE_DATE_TIME = 48;
    public static final int FIELDS_TYPE_DOUBLE = 240;
    public static final int FIELDS_TYPE_LONG_TEXT = 64;
    public static final int FIELDS_TYPE_FILES = 80;
    public static final int FIELDS_TYPE_TREE_NODE = 160;
    public static final int FIELDS_TYPE_BIT = 224;
    public static final int FIELDS_TYPE_GUID = 208;
    public static final int TYPE_TREE_PATH = 272;
    public static final int TYPE_HISTORY = 320;
    public static final int TYPE_HTML = 576;
    public static final int TYPE_ATTACHMENT = 336;
    public static final int TYPE_URL = 592;
    public static final int TYPE_BIS_URI = 848;
    public static final int TYPE_UNC = 1104;
    public static final int TYPE_RELATED_LINKS = 176;
    public static final int FIELDS_TYPE_TREE_ID = 288;
    public static final int EXPAND_CONSTANT_FLAG = 1;
    public static final int USE_FIELD_TYPE_FLAG = 2;
    public static final int BETWEEN_EXCLUDE_LOWER_FLAG = 4;
    public static final int BETWEEN_EXCLUDE_UPPER_FLAG = 8;
    public static final int EXPAND_VALUE_FLAG = 16;
}
