// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.wss;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.types.AnyContentType;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.wss._ListsSoap_UpdateList;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _ListsSoap_UpdateList
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String listName;
    protected AnyContentType listProperties;
    protected AnyContentType newFields;
    protected AnyContentType updateFields;
    protected AnyContentType deleteFields;
    protected String listVersion;

    public _ListsSoap_UpdateList()
    {
        super();
    }

    public _ListsSoap_UpdateList(
        final String listName,
        final AnyContentType listProperties,
        final AnyContentType newFields,
        final AnyContentType updateFields,
        final AnyContentType deleteFields,
        final String listVersion)
    {
        // TODO : Call super() instead of setting all fields directly?
        setListName(listName);
        setListProperties(listProperties);
        setNewFields(newFields);
        setUpdateFields(updateFields);
        setDeleteFields(deleteFields);
        setListVersion(listVersion);
    }

    public String getListName()
    {
        return this.listName;
    }

    public void setListName(String value)
    {
        this.listName = value;
    }

    public AnyContentType getListProperties()
    {
        return this.listProperties;
    }

    public void setListProperties(AnyContentType value)
    {
        this.listProperties = value;
    }

    public AnyContentType getNewFields()
    {
        return this.newFields;
    }

    public void setNewFields(AnyContentType value)
    {
        this.newFields = value;
    }

    public AnyContentType getUpdateFields()
    {
        return this.updateFields;
    }

    public void setUpdateFields(AnyContentType value)
    {
        this.updateFields = value;
    }

    public AnyContentType getDeleteFields()
    {
        return this.deleteFields;
    }

    public void setDeleteFields(AnyContentType value)
    {
        this.deleteFields = value;
    }

    public String getListVersion()
    {
        return this.listVersion;
    }

    public void setListVersion(String value)
    {
        this.listVersion = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "listName",
            this.listName);
        this.listProperties.writeAsElement(
            writer,
            "listProperties");
        this.newFields.writeAsElement(
            writer,
            "newFields");
        this.updateFields.writeAsElement(
            writer,
            "updateFields");
        this.deleteFields.writeAsElement(
            writer,
            "deleteFields");
        XMLStreamWriterHelper.writeElement(
            writer,
            "listVersion",
            this.listVersion);

        writer.writeEndElement();
    }
}
