// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the repository root.

 /*
 * This file was automatically generated by com.microsoft.tfs.core.ws.generator.Generator
 * from the /complexType.vm template.
 */
package ms.wss;

import com.microsoft.tfs.core.ws.runtime.*;
import com.microsoft.tfs.core.ws.runtime.serialization.*;
import com.microsoft.tfs.core.ws.runtime.types.*;
import com.microsoft.tfs.core.ws.runtime.types.AnyContentType;
import com.microsoft.tfs.core.ws.runtime.util.*;
import com.microsoft.tfs.core.ws.runtime.xml.*;

import ms.wss._ListsSoap_GetListItemChangesSinceToken;

import java.lang.String;

import java.util.ArrayList;
import java.util.List;

import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;

/**
 * Automatically generated complex type class.
 */
public class _ListsSoap_GetListItemChangesSinceToken
    implements ElementSerializable
{
    // No attributes    

    // Elements
    protected String listName;
    protected String viewName;
    protected AnyContentType query;
    protected AnyContentType viewFields;
    protected String rowLimit;
    protected AnyContentType queryOptions;
    protected String changeToken;
    protected AnyContentType contains;

    public _ListsSoap_GetListItemChangesSinceToken()
    {
        super();
    }

    public _ListsSoap_GetListItemChangesSinceToken(
        final String listName,
        final String viewName,
        final AnyContentType query,
        final AnyContentType viewFields,
        final String rowLimit,
        final AnyContentType queryOptions,
        final String changeToken,
        final AnyContentType contains)
    {
        // TODO : Call super() instead of setting all fields directly?
        setListName(listName);
        setViewName(viewName);
        setQuery(query);
        setViewFields(viewFields);
        setRowLimit(rowLimit);
        setQueryOptions(queryOptions);
        setChangeToken(changeToken);
        setContains(contains);
    }

    public String getListName()
    {
        return this.listName;
    }

    public void setListName(String value)
    {
        this.listName = value;
    }

    public String getViewName()
    {
        return this.viewName;
    }

    public void setViewName(String value)
    {
        this.viewName = value;
    }

    public AnyContentType getQuery()
    {
        return this.query;
    }

    public void setQuery(AnyContentType value)
    {
        this.query = value;
    }

    public AnyContentType getViewFields()
    {
        return this.viewFields;
    }

    public void setViewFields(AnyContentType value)
    {
        this.viewFields = value;
    }

    public String getRowLimit()
    {
        return this.rowLimit;
    }

    public void setRowLimit(String value)
    {
        this.rowLimit = value;
    }

    public AnyContentType getQueryOptions()
    {
        return this.queryOptions;
    }

    public void setQueryOptions(AnyContentType value)
    {
        this.queryOptions = value;
    }

    public String getChangeToken()
    {
        return this.changeToken;
    }

    public void setChangeToken(String value)
    {
        this.changeToken = value;
    }

    public AnyContentType getContains()
    {
        return this.contains;
    }

    public void setContains(AnyContentType value)
    {
        this.contains = value;
    }

    public void writeAsElement(
        final XMLStreamWriter writer,
        final String name)
        throws XMLStreamException
    {
        writer.writeStartElement(name);

        // Elements
        XMLStreamWriterHelper.writeElement(
            writer,
            "listName",
            this.listName);
        XMLStreamWriterHelper.writeElement(
            writer,
            "viewName",
            this.viewName);
        this.query.writeAsElement(
            writer,
            "query");
        this.viewFields.writeAsElement(
            writer,
            "viewFields");
        XMLStreamWriterHelper.writeElement(
            writer,
            "rowLimit",
            this.rowLimit);
        this.queryOptions.writeAsElement(
            writer,
            "queryOptions");
        XMLStreamWriterHelper.writeElement(
            writer,
            "changeToken",
            this.changeToken);
        this.contains.writeAsElement(
            writer,
            "contains");

        writer.writeEndElement();
    }
}
